<Project>
  <ItemGroup>
    <PackageVersion Include="ExcelDna.AddIn" Version="1.8.0" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" />
    <PackageVersion Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageVersion Include="Polyfill" Version="5.0.0" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="System.Text.Json" Version="8.0.5" />
    <PackageVersion Include="TUnit" Version="1.58.0" />
    <PackageVersion Include="TUnit.Mocks.Http" Version="1.58.0" />
  </ItemGroup>
</Project>
